### ISSUE TITLE
Can shouldRequireConsent = false, and still display the Banner?

### ISSUE THREAD

**Issue by s-herbert** [segmentio/consent-manager#131]
Hi,

I find it strange that `shouldRequireConsent` is coupled with banner visibility:

> Return true to show the consent banner and wait for consent (if no consent has been given yet). Return false to **not show the consent banner** and start tracking immediately (unless the user has opted out). 

In the US (or non-EU), we want this to be false BUT STILL display the banner so that users get the message and can change their preferences. 

My current solution was to hand-make a banner when `inEU` returns false -- but i feel like there must be another way. 

Anyone happen to know what I missed?

Thanks

P.S. using the react version of ConsentManager

**Comment by borisrorsvort** [comment]
@s-herbert lot’s of privacy issues still. I noticed this happens too https://github.com/segmentio/consent-manager/issues/122

**Comment by felipe-najson** [comment]
Hi @s-herbert, sorry for the late reply. 
That's the expected behavior of the "shouldRequireConsent" property.

In your case you want to start a tracking immediately and show consent you can use the property "implyConsentOnInteraction = true"
which will start tracking immediately once the user interacts with the page but will show the banner once in case the user prefer to change preferences.

Another idea that comes to mind is that you add a button which opens the consent table using the "openConsentManager" event in case the user wants to change their preferences.
Here is described: https://github.com/segmentio/consent-manager#utility-functions

Feel free to ask any other questions, Segment team.

**Comment by felipe-najson-ntf** [comment]
Hi @s-herbert, sorry for the late reply.
That's the expected behavior of the "shouldRequireConsent" property.

In your case you want to start a tracking immediately and show consent you can use the property "implyConsentOnInteraction = true"
which will start tracking immediately once the user interacts with the page but will show the banner once in case the user prefer to change preferences.

Another idea that comes to mind is that you add a button which opens the consent table using the "openConsentManager" event in case the user wants to change their preferences.
Here is described: https://github.com/segmentio/consent-manager#utility-functions

Feel free to ask any other questions, Segment team.
