### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by Dezzymei** [segmentio/consent-manager#135]
Using React 17.x I get this error whenever I use the consent manager.

**Comment by felipe-najson-ntf** [comment]
Hi @Dezzymei, the issue still persists. Apparently the warning is not due to Consent Manager by itself but to a third-party library that uses this method. I will be investigating these days to update that dependency in order to remove the warning. I will keep you updated.

Thanks, segment team.

**Comment by felipe-najson-ntf** [comment]
Update. @Dezzymei 

As we suspected the problem is in a third party library called "react-emotion". For my research we would need to migrate to "@emotion-styled" as documented here.
https://www.npmjs.com/package/react-emotion
Which is not straightforward. At the moment it is a warning so we will lower the priority of this issue and discuss with the team what decision to make.

Thanks for your contribution. Segment team

**Comment by Dezzymei** [comment]
I have created a PR for this: https://github.com/segmentio/consent-manager/pull/216
