### ISSUE TITLE
Saving preferences starts a reloading loop

### ISSUE THREAD

**Issue by MoSattler** [segmentio/consent-manager#146]
We're currently trying to use consent-manager for our **nextJS** app, but we keep ending up in a refresh loop. 

Our code is fairly simple
```javascript
  <ConsentManager
    writeKey={process.env.WRITE_KEY}
    shouldRequireConsent={inRegions(['CA', 'EU'])}
  />
```

After the preference was selected by the user, and then saved, the page refreshes, which is expected. But after the app renders, including the ConsentManager, the following happens:

1. `ConsentManagerBuilder.componentDidMount` [calls the inititalise](https://github.com/segmentio/consent-manager/blob/master/src/consent-manager-builder/index.tsx#L164) function.
2. [`initialise` function](https://github.com/segmentio/consent-manager/blob/master/src/consent-manager-builder/index.tsx#L219-L226) calls the `conditionallyLoadAnalytics` function.
3. `conditionallyLoadAnalytics` [refreshes the page again](https://github.com/segmentio/consent-manager/blob/5db5e01915c03af9a791416ab8734829a2d0e52a/src/consent-manager-builder/analytics.ts#L76-L81).
4. Page refreshes and we start over with 1.

Is there anything we have to do to prevent consent-manager from getting stuck in a refresh loop? What would normally stop the chain of events above?

**Comment by epragalakis** [comment]
any updates on this?

**Comment by hoomanaskari** [comment]
Having the same issue!

**Comment by felipe-najson-ntf** [comment]
Hi everyone, it seems that the problem is that analytics.load() is executing twice and therefore it is in loop. I will be working to fix this problem these days.

I would like to know how you are loading the segment snippet in order to reproduce your problem.

Thanks, segment team!

**Comment by felipe-najson-ntf** [comment]
Hi everyone! @MoSattler @epragalakis @hoomanaskari. Last comment, the problem was the one described above, we left a guide on how to integrate Consent Manager with Next.js in our documentation. 
https://github.com/segmentio/consent-manager#example-in-nextjs

Any problem, please open another issue. Thanks, segment team.

**Comment by labananala** [comment]
Hi @felipe-najson-ntf , thanks for looking. I also have this same reloading issue with `ConsentManagerBuilder`, but my team is not using Next.js. We are temporarily working around it by using a forked version of this consent-manager repo with a small change in `ConsentManagerBuilder`- passing in `shouldReload = false` into the `conditionallyLoadAnalytics()` call [under the isConsentRequired line](https://github.com/segmentio/consent-manager/blob/master/src/consent-manager-builder/index.tsx#L237). It seems to be working fine, and it fixed our reloading issue, but would love if we could get off this forked version. This "fix" may or may not be the technically correct one but it works for us, and I'm just hoping that might spark ideas from you on why this reloading would otherwise be happening in our vanilla React/Redux app.
