### ISSUE TITLE
Destination fetch frequently fails

### ISSUE THREAD

**Issue by jescalan** [segmentio/consent-manager#15]
I deployed this consent manager on Friday and since then I have had hundreds of runtime errors reported with a "failed to fetch" exception on the destinations call [here](https://github.com/segmentio/consent-manager/blob/master/src/consent-manager-builder/fetch-destinations.js#L5) - I'm not sure what's causing the issue, but there's no way for me to see without error handling on the fetch call. Will put in a pull request to add this, just wanted to have this issue as a note!

**Comment by Rowno** [comment]
Thanks for trying out the consent manager!

The only things I can think of that would cause fetch errors would be an invalid write key (which I'm assuming isn't the case) or ad blockers (they tend to block cdn.segment.com).

**Comment by jescalan** [comment]
Hmm, it certainly could be ad blockers. Do you know if there's any way to detect whether the connection failed because of an issue with segment vs it being blocked by an ad blocker? If so, it would probably make for fewer noisy runtime errors if adblock failures were silent...

**Comment by Rowno** [comment]
I don't think it's possible to detect ad blocker errors because the browser doesn't expose any details in network errors (for security reasons), not even the error codes that show up in the dev tools. The only way would be to do something like: https://stackoverflow.com/questions/4869154/how-to-detect-adblock-on-my-website

But we can definitely handle the errors so that they're no longer uncaught rejections, I'm just not sure what the best approach would be.

**Comment by Rowno** [comment]
One idea would be to add an `onError` callback option that catches the errors when it's defined, and continue to not handle the errors when it's not defined.

**Comment by nettofarah** [comment]
I like the idea of providing an `onError` callback :)

**Comment by mantagen** [comment]
Looks like this just needs a line of documentation, then issue can be closed?

**Comment by Edjevw12** [comment]
Any progress on this?

**Comment by felipe-najson-ntf** [comment]
Hello everyone, it has been a long time since this problem, with @fforres merge #31, it was fixed. The library currently supports the onError callback option that catches errors when defined and continues without handling errors when undefined.
Therefore I will be closing this problem. 

Segment team
