### ISSUE TITLE
Standalone script with callback function doesn't work on IE?

### ISSUE THREAD

**Issue by BrunoBoehm** [segmentio/consent-manager#21]
Hi @Rowno  
I'm using the standalone script and since I wanted to make sure it'd work on IE, didn't use the data-attributes and went for the callback function "advanced" implementation. However it looks like it's still not working on IE: any idea for a fix?

Thanks, 
Bruno

**Comment by Rowno** [comment]
I never got around to testing IE because I don't have access to a Windows machine at work, but I just did some brief testing using my personal gaming PC and it looks like we're using a couple of ES6 features like `array.find()`, `string.includes()` and `Promise` that aren't supported by IE. Edge seems to work fine though.

If you include the [babel-polyfill](https://babeljs.io/docs/en/babel-polyfill.html) on the page **before** the consent-manager, it *should* work.

Otherwise I'm open to pull requests that fix the incompatibilities (I've already removed the `string.includes()` usage).

**Comment by BrunoBoehm** [comment]
Awesome. So for the record I went the easy way and added the polyfill using the script from CDNJS in my header before loading the consent manager. Tested it on several browsers and it seems to solve the issue on most. Thanks @Rowno 
 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js" integrity="sha256-WRc/eG3R84AverJv0zmqxAmdwQxstUpqkiE+avJ3WSo=" crossorigin="anonymous"></script>`

**Comment by Rowno** [comment]
Cool, thanks for the update.
