### ISSUE TITLE
Feature Request - onClose on ConsentManager

### ISSUE THREAD

**Issue by ahallora** [segmentio/consent-manager#66]
How can I define a custom callback on closing of the ConsentManager?

E.g. to hide the container div when the consent has been dismissed, accepted or denied (https://github.com/segmentio/consent-manager#closebehavior) 

```jsx
<ConsentManager
  writeKey={SEGMENT_KEY}
  shouldRequireConsent={inEU}
  closeBehavior={"accept"}
  ...
  onClose={closeOption => console.log(`User closed and selected: ${closeOption}`)}
/>
```

**Comment by ahallora** [comment]
Also, a feature to easily check if user has accepted cookies would be awesome. :) 

Right now I'm doing a very bad lookup for the localstorage value, and it just feels wrong doing so. 

```jsx
    const [userDidAccept, setUserDidAccept] = React.useState(false);

    const checkAnalytics = React.useCallback(() => {
        let checkAnalyticsTimer = null;
        checkAnalyticsTimer = clearTimeout(checkAnalyticsTimer);

        if (!userDidAccept) {
            if (window.localStorage.getItem("ajs_user_traits") !== null) {
                setUserDidAccept(true);
            } else {
                checkAnalyticsTimer = setTimeout(checkAnalytics, 250);
            }
        }
    }, [userDidAccept]);

    React.useEffect(() => checkAnalytics(), [checkAnalytics]);
   
   return(
      <div style={{display: userDidAccept ? "none" : "block" }}>
         <ConsentManager/>
      </div>
   );
```

**Comment by felipe-najson-ntf** [comment]
Hi @ahallora, in the current version there is no function to call a callback function but I will add it to the backlog to consider it in the future!
On the other hand the banner will close only when you accept the consent, therefore you don't have to handle that with a callback function. Otherwise you can change certain properties like "implyConsentOnInteraction 'or" shouldRequireConsent" to give it another behavior. I hope this helps!

Please check the lastest version of the library to know all the new features.

Thanks. segment team.
