### ISSUE TITLE
On saveConsent(true) does not update state.havePreferencesChanged

### ISSUE THREAD

**Issue by EfosaSO** [segmentio/consent-manager#92]
We ran into this weird issue when loading the consent manager using the consent manager builder.

We have a button that "Allows all cookies" and on first time load that button would run successfully but the page never reloaded, neither did the analytics initialise.

To get it to work, we would have to disable a cookie destination and save, which ran the `handleSetPreferences` and that updated the state as seen [here](https://github.com/segmentio/consent-manager/blob/ca3a9cfdd698dc1cd1cee66bd3abd8993d29fa04/src/consent-manager-builder/index.tsx#L233). That wasn't an ideal fix.

We can't find where in the `saveConsent` it updates the `havePreferencesChanged` in the state; it's not in the `mergePreferences` either. The only way we fixed this issue was by running the `setPreferences(true)` function before the `saveConsent(true)` as that updated the state.

**Comment by bryszard** [comment]
I have a similar problem - using the `ConsentManagerBuilder` we have the banner and we use `closeBehavior="accept"` option, so my expectation is that when I dismiss the banner, preferences will be save to the cookie. 

However, this is not the case. The condition in [here](https://github.com/segmentio/consent-manager/blob/master/src/consent-manager-builder/index.tsx#L292) returns `false` and the banner reappears after page reload.

As @EfosaSO described, the reason is the `state.havePreferencesChanged` value which is not changed anywhere in the process.

**Comment by camsloanftc** [comment]
I was struggling with this as well in using ConsentManagerBuilder. I ended up doing a custom `opIn` function:
```js
function optIn ({segment}) {
  const allPreferencesTrue = segment.destinations.reduce(
    (acc, current) => {
      return {
        ...acc,
        [current.id]: true,
      }
    },
    {}
  )
  segment.setPreferences(allPreferencesTrue)
  segment.saveConsent(true, false) // the second boolean skips the page reload.
}
```

Thanks to "setPreferences" above, this triggers the consent to actually save the cookie because it matches the `prevState.havePreferencesChanged` condition in this part of the code:
```js
// If preferences haven't changed, don't reload the page as it's a disruptive experience for end-users
if (prevState.havePreferencesChanged || newDestinations.length > 0) {
  savePreferences({ destinationPreferences: destinationPreferences, customPreferences: customPreferences, cookieDomain: cookieDomain });
  conditionallyLoadAnalytics({
      writeKey: writeKey,
      destinations: destinations,
      destinationPreferences: destinationPreferences,
      isConsentRequired: isConsentRequired,
      shouldReload: shouldReload,
      defaultDestinationBehavior: defaultDestinationBehavior
  });
}}
```

I have to say this has been a pretty frustrating experience so far.
